### ISSUE TITLE
Add calculation of lepton mini-isolation from miniAOD

### ISSUE THREAD

**Issue by wulsin** [OSU-CMS/OSUT3Analysis#21]
This calculation is described in this HN post:
https://hypernews.cern.ch/HyperNews/CMS/get/susy/1991.html

**Comment by jalimena** [comment]
This issue seems outdated and we shouldn't do it. @bpf6qc , @aehart , @btcardwell , do you agree, can we close this issue?

**Comment by btcardwell** [comment]
Closing this issue sounds good to me.

**Comment by bpf6qc** [comment]
Starting in 92X there is a "miniPFIsolation()" method in DataFormats/PatCandidates/interface/Lepton.h, so this is outdated for 2017 data. It looks to be still needed in 7-8XY; none of us use it I don't think, and I can't immediately find recommendations for cone sizes in those eras.

My say is to close the issue and re-raise it if, for example, it's being used in 2017-8 data and people want to backport it into older data.
