### ISSUE TITLE
mergeOutput.py condor submission broken

### ISSUE THREAD

**Issue by lantone** [OSU-CMS/OSUT3Analysis#22]
Hi @prbbing 

It looks like condor submission of merging jobs is not working:

```
                                                                                                                                                                    <~> mergeOut.py -l QCDPreselectionOptions.py -w NOV23__QCDPreselection -c
```

...
...
...
......................Using Condor!...........................
Submitting job(s)
ERROR: "condorMerging.sub" doesn't contain any "queue" commands -- no jobs queued

Could you take a look at this?  Thanks,

Jamie

**Comment by prbbing** [comment]
I’ll have a look

**Comment by prbbing** [comment]
Actually I just found that the current feature does not buy us much time I will think about it. Please use the interactive way for now. 

Multithreaded is the right way to go.

**Comment by jalimena** [comment]
I think this issue has either been fixed already, or isn't a big deal and we should close this ticket and not do it. @bpf6qc , @aehart , @btcardwell , do you agree?

**Comment by bpf6qc** [comment]
Condor merging certainly works, so I'm closing this issue.
