### ISSUE TITLE
pu scale factor producing not working

### ISSUE THREAD

**Issue by lantone** [OSU-CMS/OSUT3Analysis#26]
I get the same error (below) when running on either a miniAOD file or a skim file.

ERROR: did not find any collections that match input tag:  InputTag:  label = PUScalingFactorProducer, instance = eventvariables, with type:  N3edm6HandleIN3osu13EventvariableEEE
----- Begin Fatal Exception 22-Dec-2015 12:47:04 EST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing run: 1 lumi: 1479 event: 3228953
   [1] Running path 'QCDMuonControlRegion'
   [2] Calling event method for module Plotter/'QCDMuonControlRegionPlotter'
Exception Message:
Principal::getByLabel: Found zero products matching all criteria
Looking for type: osu::Eventvariable
Looking for module label: PUScalingFactorProducer
Looking for productInstanceName: eventvariables

**Comment by prbbing** [comment]
Please point me to the *_cfg.py file you are using.

**Comment by lantone** [comment]
Sure thing, you can find it here:
/home/lantonel/CMSSW_7_4_5_ROOT5/src/DisplacedSUSY/BackgroundStudies/test/QCDMuonControlRegion_cfg.py

I forgot to mention - the problem only comes up when trying to use the PU SF as a weight for plotting.

**Comment by prbbing** [comment]
And your QCDMuonControlRegion selections.

**Comment by prbbing** [comment]
I can not reproduce what you saw.

Before updating git, I made a skim and run over the skim it worked fine. The pileup scaling factor histogram is filled. 

Then I updated git to what it is now, it still works.

**Comment by lantone** [comment]
Ok, thanks for looking into it.  When I get time I'll push everything I'm using into git, update anything else that's changed in the meantime, and see if I'm still getting the error.

**Comment by jalimena** [comment]
Unclear to me if this was ever fixed. I haven't seen such an error, so I'm assuming yes?

**Comment by bpf6qc** [comment]
PUScalingFactorProducer has been overhauled since this and it surely works at the moment.
